Rename and update master branch references to main
elyra-ai/website pull request #1
Opened 2022-05-27 17:13 UTC by akchinSTC

2022-06-06 14:46 UTC, ptitzler commented on .gitignore
> +#pycharm
Intentional changes?

2022-06-06 14:47 UTC, ptitzler commented on src/pages/common-canvas/callbacks.mdx
> +To overwrite the content, you can return either a string or a React element. If your code returns null for a particular type of tip, common-canvas will display the default tip for that object. For an
Canvas repo is not renaming the `master` branch as part of this effort.

```suggestion
To overwrite the content, you can return either a string or a React element. If your code returns null for a particular type of tip, common-canvas will display the default tip for that object. For an example of an implementation for a tipHandler, see App.js in the test harness code (https://github.com/elyra-ai/canvas/blob/master/canvas_modules/harness/src/client/App.js).
```

2022-06-06 14:49 UTC, ptitzler commented on src/pages/common-canvas/canvas-controller/canvas-controller-api.mdx
> +//  https://github.com/elyra-ai/pipeline-schemas/blob/main/common-canvas/palette/palette-v3-schema.json
```suggestion
//  https://github.com/elyra-ai/pipeline-schemas/blob/master/common-canvas/palette/palette-v3-schema.json
```

2022-06-06 14:49 UTC, ptitzler commented on src/pages/common-canvas/canvas-controller/canvas-controller-api.mdx
> +//  https://github.com/elyra-ai/pipeline-schemas/blob/main/common-canvas/palette/palette-v3-schema.json
```suggestion
//  https://github.com/elyra-ai/pipeline-schemas/blob/master/common-canvas/palette/palette-v3-schema.json
```

2022-06-06 14:51 UTC, ptitzler requested changes
Need to coordinate with the canvas team.

2022-06-14 17:11 UTC, akchinSTC commented on .gitignore
> +#pycharm
yes

2022-06-14 18:08 UTC, merged